### ISSUE TITLE
Not accurate compared to CC

### ISSUE THREAD

**Issue by Beyley** [DOOBW/OC-GPS#1]
This does not seem to be very accurate compared to the CC version, even when using the exact same setup for both.
![javaw_ojTo1vKVl0](https://user-images.githubusercontent.com/34501060/80143709-15f6b380-8562-11ea-98ec-aa867ccd839c.png)
![javaw_l1rSZ2mur6](https://user-images.githubusercontent.com/34501060/80143778-31fa5500-8562-11ea-96e2-d75f3fcab24f.png)
![javaw_pQN8eQ7Kb9](https://user-images.githubusercontent.com/34501060/80143911-70900f80-8562-11ea-86dd-ab916176cb35.png)
as you can see, I'm running gps locate from the same spot with the same setup and getting the correct position using CC and a wrong position using OC

**Comment by DOOBW** [comment]
This version uses only 3 satellites, which makes it possible to obtain exact coordinates only in 50% of cases.
I can do for 4 satellites, then the accuracy will always be 100%, but will not work with 3 satellites.

**Comment by Beyley** [comment]
Couldn't it detect if there was 4 satellites and switch to that mode if there are, and when there are 3 just use 3?

**Comment by credomane** [comment]
I've been looking over the code for both CC-GPS and OC-GPS. For the most part they seem to be the exact some thing so they should yield the exact same results but they don't always. In doing the comparison I noticed two bugs in the OC-GPS implementation. After fixing them I'm, so far, failing to get bad results with 4 GPS microcontrollers. I'll make a PR later but for now here are the two fixes:
https://github.com/DOOBW/OC-GPS/blob/0c6cec6467abc1e29196bf8f49c295bc1fd7015a/usr/lib/gps.lua#L61 Problem: sub()'ing the wrong way. Fixed with: `    local ey = norm(sub(a2c, mul(ex, i)))`

https://github.com/DOOBW/OC-GPS/blob/0c6cec6467abc1e29196bf8f49c295bc1fd7015a/usr/lib/gps.lua#L74 Problem: add()'ing when it should be sub()'ing. Fixed with: `        local result2 = sub(result, mul(ez, z))`
